linters-settings:
  cyclop:
    max-complexity: 10
  errcheck:
    check-type-assertions: true
    check-blank: true
  forbidigo:
    forbid:
      - fmt.Errorf # consider errors.Errorf in github.com/pkg/errors
      - fmt.Print.* # too much log noise
  gocognit:
    min-complexity: 12
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
#    disabled-checks:
#      - dupImport # https://github.com/go-critic/go-critic/issues/845
  gocyclo:
    min-complexity: 12
  golint:
    min-confidence: 0.8
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
# Do we want to use linters log? Should use the depguard too then?
  govet:
    check-shadowing: false
    settings:
      printf:
        funcs:
          - (github.com/sirupsen/logrus).Infof
          - (github.com/sirupsen/logrus).Warnf
          - (github.com/sirupsen/logrus).Errorf
          - (github.com/sirupsen/logrus).Fatalf
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: true
    require-specific: false
  wsl:
    allow-cuddle-declarations: true
    allow-trailing-comment: true
    force-case-trailing-whitespace: true
    force-err-cuddling: true
    allow-separated-leading-comment: false

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocognit
    - gocyclo
    - godot
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: true
  fix: false

run:
  skip-dirs:
    - mock/*
  modules-download-mode: readonly

severity:
  default-severity: error