name: Build Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      env:
        GO111MODULE: "on"
      with:
        go-version: 1.17
      id: go  

    - name: Get Dependencies
      run: go mod download

    - name: Test
      run: go test -v ./...
    
    - name: Build Step
      run: go build -o notif cmd/main.go