name: notif-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      env:
        GO111MODULE: "on"
      with:
        go-version: 1.17
      id: go  

    - name: Get Dependencies
      run: go mod download

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.1.0
    
    - name: Run Test
      rub: go test -v ./...

    - name: Build binary
      run: go build -o notif cmd/main.go